name: Publish

on:
  push:

jobs:
  test:
    name: Test and format
    uses: jb3rndt/PersistentBottomNavBarV2/.github/workflows/tests.yaml@master

  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    needs: test

    steps:

      - name: Publish package to pub.dev
        uses: sakebook/actions-flutter-pub-publisher@v1.4.0
        with:
          credential: ${{ secrets.PUB_CREDENTIALS }}
          flutter_package: true
          skip_test: true
          dry_run: true
