name: Tests
on:
  push:
    branches:
      - master
  pull_request:

env:
  FLUTTER_VERSION: '2.8.1'

jobs:
  tests:
    name: Unit tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019, macos-10.15]
    steps:
      - name: Cache
        id: cache-flutter
        uses: actions/cache@v3.0.1
        with:
          path: ${{ runner.tool_cache }}/flutter
          key: flutter-${{ runner.os }}-${{ env.FLUTTER_VERSION }}

      - name: Set up Flutter if not cached
        if: steps.cache-flutter.outputs.cache-hit != 'true'
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
      - run: flutter doctor -v

      # Checkout and get packages.
      - name: Checkout
        uses: actions/checkout@v2
      - run: flutter pub get -v

      # Analyze, check formatting, and run unit tests.
      - run: flutter analyze
      - name: Ensure the Dart code is formatted correctly
        run: flutter format --set-exit-if-changed --dry-run .
      - name: Run Flutter unit tests
        run: flutter test --coverage
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
